version: '2'

volumes:
  mysql: {}

networks:
  learngonet:
    driver: bridge

services:
  api-mysql:
    build: .
    image: 'dimaskiddo/api-mysql:latest'
    networks:
      - learngonet
    ports:
      - 3000:3000
    restart: always

  mysql:
    image: 'dimaskiddo/alpine:mysql-10.2'
    networks:
      - learngonet
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dbs
    volumes:
      - mysql:/var/lib/mysql/data
    restart: always

  adminer:
    image: 'dimaskiddo/alpine:adminer-4.6.2'
    networks:
      - learngonet
    ports:
      - 8080:8080
    restart: always
